name: jhub-apps-dev
channels:
  - conda-forge
dependencies:
  - python ==3.9
  - fastapi
  - httpx
  - python-multipart
  - uvicorn
  - jupyterhub
  - jupyter
  - plotlydash-tornado-cmd
  - bokeh-root-cmd
  - jhsingle-native-proxy
  - black
