name: jhub-apps-dev
channels:
  - conda-forge
dependencies:
  - flask
  - jupyterhub
  - jupyter
  - plotlydash-tornado-cmd
  - bokeh-root-cmd
  - jhsingle-native-proxy
  - pytest
  - black
  - panel
  - bokeh
  - voila
  - dash
  - streamlit
  - pytest-playwright
