name: build

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1.4.3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment-dev.yml
        create-args: >-
          python=${{ matrix.python-version }}
          numpy

    - name: Install JHub Apps
      run: |
        pip install .

    - name: Install Test dependencies
      run: |
        pip install flake8 pytest

    - name: Lint with black
      uses: psf/black@stable

