name: build

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        test_type:
          - tests
          - tests_e2e
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1.4.3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment-dev.yml
        create-args: >-
          python=${{ matrix.python-version }}
          numpy

    - name: Install JHub Apps
      run: |
        pip install .

    - name: Lint with black
      uses: psf/black@stable

    - name: Install Playwright
      if: matrix.test_type == 'tests_e2e'
      run: |
        plawright install

    - name: Run Tests
      run: |
        pytest jhub_apps/${{ matrix.test_type }} -vvv -s

    - name: Test playwright
      run: |
        playwright install
        pytest jhub_apps/tests_e2e -vvv -s
